apiVersion: v1
data:
  aws_access_key_id: QUtJQVNLQUIzUkxQU09NTVMzRkE=
  aws_secret_access_key: a1M5R0ZPa0VVZklXTG05TUVwQTQ1RmZRUkNYZlpaaHhmRGRZd0hBMw==
kind: Secret
metadata:
  creationTimestamp: null
  name: aws
type: string 
